version: "3.4"

services:

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "${SSL_PORT}:${SSL_PORT}"
    env_file:
      - .env
    volumes:
      - ./data/nginx/templates:/etc/nginx/templates
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    container_name: cert
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
